### ISSUE TITLE
[To-do] 1st enhancement

### ISSUE THREAD

**Issue by OlivierAddons** [OlivierAddons/Oracle-ddlLibrary#1]
- [ ] create a method to modify the type of a column
- [ ] create a method to add a not null constraint
- [ ] create a method to remove a not null constraint
